# Generated by Django 4.1.1 on 2022-10-14 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 13, 25, 58, 337515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unité_poids', models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='g', max_length=200)),
                ('date_souvrage_aprés', models.IntegerField(default=25)),
                ('unité_devise', models.CharField(choices=[('din tun', 'din tun'), ('din alg', 'din alg')], default='din tun', max_length=200)),
                ('nb_production_naturel', models.IntegerField(default=8)),
                ('nb_mortalité_naturel', models.IntegerField(default=2)),
                ('consomation_naturel', models.IntegerField(default=7500)),
                ('coup_alimentation', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
