# Generated by Django 4.1.1 on 2022-10-31 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 16, 20, 50, 545398, tzinfo=datetime.timezone.utc)),
        ),
    ]
