# Generated by Django 4.1.6 on 2023-02-08 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 2, 9, 19, 616085, tzinfo=datetime.timezone.utc)),
        ),
    ]
