# Generated by Django 4.1.6 on 2023-02-19 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_race_race_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 16, 4, 7, 818084, tzinfo=datetime.timezone.utc)),
        ),
    ]
