# Generated by Django 4.1.6 on 2023-02-19 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='Race',
            new_name='race',
        ),
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 16, 4, 59, 54187, tzinfo=datetime.timezone.utc)),
        ),
    ]
