# Generated by Django 4.1.6 on 2023-03-14 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 16, 46, 29, 989703, tzinfo=datetime.timezone.utc)),
        ),
    ]
