# Generated by Django 3.2.18 on 2023-03-22 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(default='____', max_length=200)),
                ('type', models.CharField(choices=[('Les_maladies_dermatologiques', 'Les maladies dermatologiques'), ('Les_maladies_respiratoires', 'Les maladies respiratoires'), ('Les_maladies_digestives', 'Les maladies digestives'), ("Les_maladies_de_l'appareil_urinaire", "Les maladies de l'appareil urinaire"), ('La_maladie_hémorragique_du_lapin', 'La maladie hémorragique du lapin'), ('Les_tumeurs', 'Les tumeurs')], default='__', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 9, 2, 23, 941757, tzinfo=utc)),
        ),
    ]
