# Generated by Django 3.2.18 on 2023-03-22 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20230322_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 9, 7, 13, 287417, tzinfo=utc)),
        ),
    ]
