# Generated by Django 4.1.7 on 2023-05-17 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 11, 40, 56, 131050, tzinfo=datetime.timezone.utc)),
        ),
    ]
