# Generated by Django 4.1.1 on 2023-06-16 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_codevirif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevirif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 19, 52, 34, 617878, tzinfo=datetime.timezone.utc)),
        ),
    ]
