# Generated by Django 4.1.1 on 2022-10-11 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Femalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('race', models.CharField(blank=True, choices=[('Gaint Flander', 'Gaint Flander'), ('Flemish Giant', 'Flemish Giant'), ('Chinchilla', 'Chinchilla'), ('New Zealand White', 'New Zealand White'), ('California', 'California'), ('Rex', 'Rex')], max_length=200, null=True)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_vent', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FemalleStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('femalle', models.DateField(blank=True, null=True)),
                ('TP', models.IntegerField(blank=True, null=True)),
                ('TM', models.IntegerField(blank=True, null=True)),
                ('TMN', models.IntegerField(blank=True, null=True)),
                ('TPnet', models.IntegerField(blank=True, null=True)),
                ('TPf', models.IntegerField(blank=True, null=True)),
                ('TMf', models.IntegerField(blank=True, null=True)),
                ('TPnetf', models.IntegerField(blank=True, null=True)),
                ('TPm', models.IntegerField(blank=True, null=True)),
                ('TMm', models.IntegerField(blank=True, null=True)),
                ('TPnetm', models.IntegerField(blank=True, null=True)),
                ('TV', models.IntegerField(blank=True, null=True)),
                ('TVm', models.IntegerField(blank=True, null=True)),
                ('TVf', models.IntegerField(blank=True, null=True)),
                ('grandprix', models.IntegerField(blank=True, null=True)),
                ('basprix', models.IntegerField(blank=True, null=True)),
                ('moyprix', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('MPN', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('MPS', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('TOPPS', models.IntegerField(blank=True, null=True)),
                ('BASPS', models.IntegerField(blank=True, null=True)),
                ('TOPPN', models.IntegerField(blank=True, null=True)),
                ('BASPN', models.IntegerField(blank=True, null=True)),
                ('cons', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Malle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('Gaint Flander', 'Gaint Flander'), ('Flemish Giant', 'Flemish Giant'), ('Chinchilla', 'Chinchilla'), ('New Zealand White', 'New Zealand White'), ('California', 'California'), ('Rex', 'Rex')], default='California', max_length=200)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_vent', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoidMalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('malle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.malle')),
            ],
        ),
        migrations.CreateModel(
            name='PoidFemalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('femalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.femalle')),
            ],
        ),
        migrations.CreateModel(
            name='ConsMalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('malle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.malle')),
            ],
        ),
        migrations.CreateModel(
            name='ConsFemalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('femalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.femalle')),
            ],
        ),
    ]
