# Generated by Django 3.2.16 on 2022-12-29 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalle',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='malle',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
