# Generated by Django 3.2.16 on 2022-12-29 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_alter_malle_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalle',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
