# Generated by Django 3.2.16 on 2022-12-29 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_alter_femalle_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalle',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='malle',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
