# Generated by Django 3.2.16 on 2023-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_auto_20221229_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malle',
            name='state',
            field=models.CharField(choices=[('femalle', 'femalle'), ('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50),
        ),
    ]
