# Generated by Django 3.2.16 on 2023-01-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0008_alter_malle_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='malle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
