# Generated by Django 3.2.16 on 2023-02-04 15:03

from django.db import migrations, models
import parent.models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0009_malle_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=parent.models.upload_to),
        ),
    ]
