# Generated by Django 3.2.16 on 2023-02-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0010_alter_malle_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consmalle',
            name='malle',
        ),
        migrations.DeleteModel(
            name='ConsFemalle',
        ),
        migrations.DeleteModel(
            name='ConsMalle',
        ),
    ]
