# Generated by Django 4.1.6 on 2023-03-14 16:46

from django.db import migrations, models
import parent.models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0011_auto_20230204_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=parent.models.upload_to),
        ),
    ]
