# Generated by Django 4.1.1 on 2022-10-23 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accouplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('date_acouplage', models.DateField(default=django.utils.timezone.now)),
                ('test', models.CharField(choices=[('pas_enceinte', 'pas enceinte'), ('enceinte', 'enceinte'), ('non_vérifié', 'non vérifié')], default='non_vérifié', max_length=200)),
                ('state', models.CharField(choices=[('avant_naissance', 'avant_naissance'), ('aprés_naissance', 'aprés_naissance')], default='avant_naissance', max_length=200)),
                ('mère', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.femalle')),
                ('père', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.malle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_souvrage', models.DateField(blank=True, null=True)),
                ('nb_lapins_nées', models.IntegerField(default=0)),
                ('nb_lapins_mortes_naissances', models.IntegerField(default=0)),
                ('acouplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lapinproduction.accouplement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LapinProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('femalle', 'femalle'), ('malle', 'malle'), ('non verifier', 'non verifier')], default='non verifier', max_length=50)),
                ('race', models.CharField(blank=True, choices=[('Gaint Flander', 'Gaint Flander'), ('Flemish Giant', 'Flemish Giant'), ('Chinchilla', 'Chinchilla'), ('New Zealand White', 'New Zealand White'), ('California', 'California'), ('Rex', 'Rex')], max_length=200, null=True)),
                ('state', models.CharField(choices=[('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_vent', models.DateField(blank=True, null=True)),
                ('groupe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lapinproduction.groupeproduction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoidLapinProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('lapin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lapinproduction.lapinproduction')),
            ],
        ),
    ]
