# Generated by Django 4.1.1 on 2022-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapinproduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accouplement',
            name='test',
            field=models.CharField(choices=[('pas_enceinte', 'pas enceinte'), ('enceinte', 'enceinte'), ('non_vérifié', 'non vérifié'), ('fausse_couche', 'fausse-couche')], default='non_vérifié', max_length=200),
        ),
    ]
