# Generated by Django 4.1.1 on 2022-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapinproduction', '0003_accouplement_date_fausse_couche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accouplement',
            name='date_fausse_couche',
        ),
        migrations.AddField(
            model_name='accouplement',
            name='date_test',
            field=models.DateField(blank=True, null=True),
        ),
    ]
