# Generated by Django 4.1.1 on 2022-10-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapinproduction', '0004_remove_accouplement_date_fausse_couche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accouplement',
            name='date_fausse_couche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
