# Generated by Django 3.2.16 on 2023-01-06 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lapinproduction', '0005_accouplement_date_fausse_couche'),
    ]

    operations = [
        migrations.AddField(
            model_name='accouplement',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
