# Generated by Django 3.2.16 on 2023-01-06 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lapinproduction', '0006_accouplement_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeproduction',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
