# Generated by Django 3.2.18 on 2023-03-22 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0040_alter_codevirif_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accouplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('date_acouplage', models.DateField(default=django.utils.timezone.now)),
                ('date_fausse_couche', models.DateField(blank=True, null=True)),
                ('date_test', models.DateField(blank=True, null=True)),
                ('test', models.CharField(choices=[('pas_enceinte', 'pas enceinte'), ('enceinte', 'enceinte'), ('non_vérifié', 'non vérifié'), ('fausse_couche', 'fausse-couche')], default='non_vérifié', max_length=200)),
                ('state', models.CharField(choices=[('avant_naissance', 'avant_naissance'), ('aprés_naissance', 'aprés_naissance')], default='avant_naissance', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Femalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to=manager.models.upload_to)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_vent', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.race')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FemalleStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('femalle', models.DateField(blank=True, null=True)),
                ('TP', models.IntegerField(blank=True, null=True)),
                ('TM', models.IntegerField(blank=True, null=True)),
                ('TMN', models.IntegerField(blank=True, null=True)),
                ('TPnet', models.IntegerField(blank=True, null=True)),
                ('TPf', models.IntegerField(blank=True, null=True)),
                ('TMf', models.IntegerField(blank=True, null=True)),
                ('TPnetf', models.IntegerField(blank=True, null=True)),
                ('TPm', models.IntegerField(blank=True, null=True)),
                ('TMm', models.IntegerField(blank=True, null=True)),
                ('TPnetm', models.IntegerField(blank=True, null=True)),
                ('TV', models.IntegerField(blank=True, null=True)),
                ('TVm', models.IntegerField(blank=True, null=True)),
                ('TVf', models.IntegerField(blank=True, null=True)),
                ('grandprix', models.IntegerField(blank=True, null=True)),
                ('basprix', models.IntegerField(blank=True, null=True)),
                ('moyprix', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('MPN', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('MPS', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('TOPPS', models.IntegerField(blank=True, null=True)),
                ('BASPS', models.IntegerField(blank=True, null=True)),
                ('TOPPN', models.IntegerField(blank=True, null=True)),
                ('BASPN', models.IntegerField(blank=True, null=True)),
                ('cons', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_souvrage', models.DateField(blank=True, null=True)),
                ('nb_lapins_nées', models.IntegerField(default=0)),
                ('nb_lapins_mortes_naissances', models.IntegerField(default=0)),
                ('acouplement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.accouplement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LapinProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to=manager.models.upload_to)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_vent', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('femalle', 'femalle'), ('malle', 'malle'), ('non verifier', 'non verifier')], default='non verifier', max_length=50)),
                ('groupe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.groupeproduction')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.race')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Malle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to=manager.models.upload_to)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('mort', 'mort'), ('vendue', 'vendue'), ('production', 'production')], default='production', max_length=50)),
                ('date_mort', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_vent', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(default=django.utils.timezone.now)),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.race')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinMalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccin', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.maladie')),
                ('malle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.malle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinLapin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccin', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('lapin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.lapinproduction')),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.maladie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinFemalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccin', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('femalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.femalle')),
                ('maladie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.maladie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoidMalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('malle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.malle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoidLapinProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('lapin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.lapinproduction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoidFemalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('femalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.femalle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accouplement',
            name='mère',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.femalle'),
        ),
        migrations.AddField(
            model_name='accouplement',
            name='père',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.malle'),
        ),
        migrations.AddField(
            model_name='accouplement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
