# Generated by Django 4.1.7 on 2023-04-02 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_coupconsomation_poidfemalle_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poidfemalle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poidlapinproduction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poidmalle',
            name='user',
        ),
        migrations.AddField(
            model_name='coupconsomation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
