# Generated by Django 4.1.7 on 2023-05-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_remove_poidfemalle_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixAliments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coupconsomation',
            name='user',
        ),
        migrations.DeleteModel(
            name='FemalleStatistique',
        ),
        migrations.DeleteModel(
            name='CoupConsomation',
        ),
    ]
