# Generated by Django 4.1.1 on 2023-06-15 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_prixaliments_remove_coupconsomation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lapinproduction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='malle',
            name='user',
        ),
        migrations.AddField(
            model_name='femalle',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lapinproduction',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='malle',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
