# Generated by Django 4.1.1 on 2023-06-15 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0005_remove_femalle_user_remove_lapinproduction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalle',
            name='test',
        ),
        migrations.RemoveField(
            model_name='lapinproduction',
            name='test',
        ),
        migrations.RemoveField(
            model_name='malle',
            name='test',
        ),
        migrations.AddField(
            model_name='femalle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lapinproduction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='malle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
