# Generated by Django 4.1.1 on 2023-06-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_femalle_test_remove_lapinproduction_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalle',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.femalle'),
        ),
        migrations.AddField(
            model_name='lapinproduction',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.lapinproduction'),
        ),
        migrations.AddField(
            model_name='malle',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.malle'),
        ),
    ]
